Repository Team-Do-Nothing/swithme-backend, pull requests merged in 2024-07, with the labels that each got.

#56 Fix: 스터디 수정 API
  src/main/java/com/donothing/swithme/dto/study/StudyUpdateRequestDto.java
Labels: bug, fix

#63 Fix: bookmarked 컬럼 추가 (북마크 유무)
  src/main/java/com/donothing/swithme/controller/StudyController.java
  src/main/java/com/donothing/swithme/dto/study/StudyDetailResponseDto.java
  src/main/java/com/donothing/swithme/dto/study/StudySearchRequest.java
  src/main/java/com/donothing/swithme/repository/StudyCustomRepositoryImpl.java
Labels: fix

#64 Feat: 스터디 방장이 스터디원을 승인 및 거절 할 수 있는 기능
  src/main/java/com/donothing/swithme/controller/StudyController.java
  src/main/java/com/donothing/swithme/domain/MemberStudy.java
  src/main/java/com/donothing/swithme/dto/study/JoinStudyRequest.java
  src/main/java/com/donothing/swithme/dto/study/StudyRegisterRequestDto.java
  src/main/java/com/donothing/swithme/repository/MemberStudyRepository.java
  src/main/java/com/donothing/swithme/repository/StudyRepository.java
  src/main/java/com/donothing/swithme/service/StudyService.java
  src/test/java/com/donothing/swithme/StudyControllerTest.java
Labels: enhancement

#65 Feat: 스터디 삭제 API
  src/main/java/com/donothing/swithme/controller/StudyController.java
  src/main/java/com/donothing/swithme/service/StudyService.java
Labels: enhancement

#69 Fix: ChallengeLogStatus 상태값 추가(활성, 비활성), 이미지 url 필수값 설정
  src/main/java/com/donothing/swithme/domain/ChallengeLog.java
  src/main/java/com/donothing/swithme/domain/ChallengeLogStatus.java
  src/main/resources/application.yml
Labels: documentation, fix
