Repository Team-Do-Nothing/swithme-backend, pull requests merged in 2024-12, with the labels that each got.

#91 Feat: 스터디 조회 시 정렬 기준 추가
  src/main/java/com/donothing/swithme/common/PagingRequest.java
  src/main/java/com/donothing/swithme/common/SortOrder.java
  src/main/java/com/donothing/swithme/repository/StudyCustomRepositoryImpl.java
Labels: enhancement, help wanted

#93 Feat: 이미지 등록/삭제 API 추가
  src/main/java/com/donothing/swithme/common/ExceptionAdvice.java
  src/main/java/com/donothing/swithme/controller/ImageController.java
  src/main/java/com/donothing/swithme/domain/ImageApiType.java
  src/main/java/com/donothing/swithme/dto/image/ImageUploadRequestDto.java
  src/main/java/com/donothing/swithme/dto/image/ImageUploadResponseDto.java
  src/main/java/com/donothing/swithme/service/s3/S3Service.java
Labels: enhancement, fix

#95 Fix: 북마크 삭제 시, 스터디 아이디로 수정
  src/main/java/com/donothing/swithme/controller/BookmarkController.java
  src/main/java/com/donothing/swithme/repository/BookmarkRepository.java
  src/main/java/com/donothing/swithme/service/BookmarkService.java
Labels: fix

#97 Fix: 스터디 수정 시 400에러
  src/main/java/com/donothing/swithme/common/ExceptionAdvice.java
  src/main/java/com/donothing/swithme/domain/StudyStatus.java
  src/main/java/com/donothing/swithme/dto/study/StudyUpdateRequestDto.java
  src/main/java/com/donothing/swithme/service/StudyService.java
Labels: bug, fix, help wanted
