Repository Team-Do-Nothing/swithme-backend, pull requests merged in 2024-11, with the labels that each got.

#86 스웨거 오류 수정
  src/main/java/com/donothing/swithme/config/SecurityConfig.java
Labels: fix

#87 댓글 관련 이슈
  src/main/java/com/donothing/swithme/repository/CommentCustomCustomRepositoryImpl.java
  src/main/java/com/donothing/swithme/repository/CommentRepository.java
  src/main/java/com/donothing/swithme/service/StudyService.java
Labels: enhancement, fix

#89 Fix: 페이징 처리 안되는 이슈 수정
  src/main/java/com/donothing/swithme/common/PagingRequest.java
  src/main/java/com/donothing/swithme/controller/StudyController.java
  src/main/java/com/donothing/swithme/dto/study/StudySearchRequest.java
  src/main/java/com/donothing/swithme/repository/StudyCustomRepositoryImpl.java
Labels: bug, fix
