Repository Team-Do-Nothing/swithme-backend, pull requests merged in 2024-06, with the labels that each got.

#43 챌린지 관련 API 오타 수정
  src/main/java/com/donothing/swithme/controller/ChallengeController.java
  src/main/java/com/donothing/swithme/service/ChallengeService.java
  src/test/java/com/donothing/swithme/ChallengeServiceTest.java
Labels: fix

#49 Feat: 스터디 내 내가 참여하고 있는 모든 챌린지 조회
  src/main/java/com/donothing/swithme/controller/ChallengeController.java
  src/main/java/com/donothing/swithme/dto/challenge/ChallengeDetailResponseDto.java
  src/main/java/com/donothing/swithme/repository/MemberChallengeRepository.java
  src/main/java/com/donothing/swithme/service/ChallengeService.java
Labels: enhancement

#51 fix: 댓글 기능 수정
  src/main/java/com/donothing/swithme/dto/study/StudyCommentReqeustDto.java
Labels: bug
